const { logger } = require('../utils/Logger');
const axios = require('axios');
const { AppError } = require('../middlewares/ErrorHandlerMiddleware');
const dayjs = require('dayjs');

const PAPER_BASE_URL = process.env.PAPER_BASE_URL;

const createInvoice = async (body, callback) => {
    try {
        // user: { name, email, phone }
        // items: [{ name, price, description }]
        // externalId: The Firebase Document ID
        const { user, items, externalId } = body;

        // 1. Format Dates to DD-MM-YYYY (Required by Paper.id)
        const invoiceDate = dayjs().format('DD-MM-YYYY');
        const dueDate = dayjs().add(1, 'day').format('DD-MM-YYYY'); // 1 Days expiry

        const isInternational = items.some(item => item.currency === 'USD');

        // 2. Construct Payload matching Paper.id Open API
        const payload = {
            invoice_date: invoiceDate,
            due_date: dueDate,
            number: `${externalId}`,
            customer: {
                id: externalId,
                name: user.name,
                email: user.email,
                phone: user.phone
            },
            items: items.map(item => {
                let finalPrice = parseFloat(item.price);
                let finalDescription = item.description || "APCS Registration";

                if (item.currency === 'USD') {
                    finalPrice = Math.round(finalPrice * 17200);
                    finalDescription = `${finalDescription} (Original: $${item.price} USD)`;
                }

                let finalDiscount = parseFloat(item.discount || 0);
                if (item.currency === 'USD' && finalDiscount > 0) {
                    finalDiscount = Math.round(finalDiscount * 17200);
                }

                return {
                    name: item.name,
                    description: finalDescription,
                    quantity: 1,
                    price: process.env.PAPER_ENV === "development" ? 10000 : finalPrice,
                    discount: process.env.PAPER_ENV === "development" ? 10000 : finalDiscount,
                    discount_type: "amount",
                    tax_id: ""
                };
            }),
            // signature_text_header: invoiceDate,
            // signature_text_footer: "APCS Committee",
            terms_condition: `
            Registration Confirmation
            Registration is considered valid only after full payment has been received as stated on the invoice.

            Non - Refundable Policy
            The registration fee is non- refundable under any circumstances, except in the case that the competition is officially canceled by the organizer.

            Compliance with Competition Rules
            Participants must comply with all competition regulations. Any violation may result in disqualification without refund.
`,
            notes: `Please complete payment before ${dueDate}.${isInternational ? '\nNote: International payment uses a fixed rate of Rp 16.900 per USD.' : ''}`,
            send: {
                email: true,
                whatsapp: true,
                sms: false
            }
        };

        logger.info(`Successfully create payment for ${user.name} with id ${externalId}`);

        // 3. Call Paper.id API using AXIOS
        const response = await axios.post(
            `${PAPER_BASE_URL}/store-invoice`,
            payload,
            {
                headers: {
                    'client_id': process.env.PAPER_CLIENT_ID,
                    'client_secret': process.env.PAPER_CLIENT_SECRET,
                    'Content-Type': 'application/json'
                }
            }
        );

        // 4. Handle Response
        // Paper.id structure: { status_code: 201, data: { ... } }
        const paperResponse = response.data;
        const invoiceData = paperResponse.data;

        // Paper.id usually returns 'payper_url' (the short link) or 'url'
        const paymentUrl = invoiceData.payper_url || invoiceData.url;

        if (!paymentUrl) {
            throw new Error("Payment URL not generated by Paper.id");
        }

        try {
            const invoiceId = invoiceData.id;

            // await axios.post(
            //     `${PAPER_BASE_URL}/sales-invoices/send-all/${invoiceId}/`,
            //     {
            //         email: {
            //             to: [user.email],
            //             cc: ['hello@apcsmusic.com']
            //         },
            //         whatsapp: { number: [String(user.phone)] },
            //         // sms: { number: [String(user.phone)] }
            //     },
            //     {
            //         headers: {
            //             'client_id': process.env.PAPER_CLIENT_ID,
            //             'client_secret': process.env.PAPER_CLIENT_SECRET,
            //             'Content-Type': 'application/json'
            //         }
            //     }
            // );

            logger.info(`Email sent successfully for Invoice ID: ${invoiceId},to :${user.email}`);

        } catch (emailError) {
            console.error("Failed to send Paper.id email:", emailError?.response?.data || emailError.message);
            logger.info(`Failed to send email for invoice ${invoiceData.number}: ${emailError.message}`);
        }

        return callback(null, {
            success: true,
            paymentUrl: `https://${paymentUrl}`, // Ensure https protocol
            invoiceId: invoiceData.id
        });
    } catch (error) {
        console.error("Paper.id Error:", error?.response?.data || error.message);
        logger.info(`fail create payment: ${error.message}}`);
        throw new AppError(
            `Failed to initiate upload: ${error.message}`,
            error.$metadata?.httpStatusCode || 500
        );
    }
}

module.exports = {
    createInvoice
}