const { logger } = require('../utils/Logger');
const axios = require('axios');
const { AppError } = require('../middlewares/ErrorHandlerMiddleware');
const dayjs = require('dayjs');

const PAPER_BASE_URL = 'https://open-api.stag-v2.paper.id/api/v1'; // Use staging URL if testing

const createInvoice = async (body, callback) => {
    try {
        // user: { name, email, phone }
        // items: [{ name, price, description }]
        // externalId: The Firebase Document ID
        const { user, items, externalId } = body;

        // 1. Format Dates to DD-MM-YYYY (Required by Paper.id)
        const invoiceDate = dayjs().format('DD-MM-YYYY');
        const dueDate = dayjs().add(3, 'day').format('DD-MM-YYYY'); // 3 Days expiry

        // 2. Construct Payload matching Paper.id Open API
        const payload = {
            invoice_date: invoiceDate,
            due_date: dueDate,
            number: `INV-${externalId}`, // Unique Invoice Number based on Firebase ID
            customer: {
                id: externalId, // Use Firebase ID as customer ID to prevent duplicates
                name: user.name,
                email: user.email,
                phone: user.phone
            },
            items: items.map(item => ({
                name: item.name,
                description: item.description || "APCS Registration",
                quantity: 1,
                price: parseInt(item.price),
                discount: 0,
                tax_id: ""
            })),
            signature_text_header: invoiceDate,
            signature_text_footer: "APCS Committee",
            terms_condition: "Please complete payment within 3 days.",
            notes: "Thank you for registering with APCS.",
            send: {
                email: true,
                whatsapp: true,
                sms: false
            }
        };

        logger.info(`Successfully create payment for ${user.name} with id ${externalId}`);

        // 3. Call Paper.id API using AXIOS
        const response = await axios.post(
            `${PAPER_BASE_URL}/store-invoice`,
            payload,
            {
                headers: {
                    'client_id': process.env.PAPER_CLIENT_ID,
                    'client_secret': process.env.PAPER_CLIENT_SECRET,
                    'Content-Type': 'application/json'
                }
            }
        );

        // 4. Handle Response
        // Paper.id structure: { status_code: 201, data: { ... } }
        const paperResponse = response.data;
        const invoiceData = paperResponse.data;

        // Paper.id usually returns 'payper_url' (the short link) or 'url'
        const paymentUrl = invoiceData.payper_url || invoiceData.url;

        if (!paymentUrl) {
            throw new Error("Payment URL not generated by Paper.id");
        }

        try {
            const invoiceId = invoiceData.id;

            // console.log("invoiceData", invoiceData)
            // console.log("url", `${PAPER_BASE_URL}/sale-invoices/send-all/${invoiceId}`)
            // console.log("user.email", user.email)
            await axios.post(
                `${PAPER_BASE_URL}/sales-invoices/send-all/${invoiceId}/`,
                {
                    email: {
                        to: [user.email],
                        cc: ['hello@apcsmusic.com']
                    },
                    whatsapp: { number: [String(user.phone)] },
                    // sms: { number: [String(user.phone)] }
                },
                {
                    headers: {
                        'client_id': process.env.PAPER_CLIENT_ID,
                        'client_secret': process.env.PAPER_CLIENT_SECRET,
                        'Content-Type': 'application/json'
                    }
                }
            );

            logger.info(`Email sent successfully for Invoice ID: ${invoiceId}`);

        } catch (emailError) {
            console.error("Failed to send Paper.id email:", emailError?.response?.data || emailError.message);
            logger.error(`Failed to send email for invoice ${invoiceData.number}: ${emailError.message}`);
        }

        return callback(null, {
            success: true,
            paymentUrl: `https://${paymentUrl}`, // Ensure https protocol
            invoiceId: invoiceData.id
        });
    } catch (error) {
        console.error("Paper.id Error:", error?.response?.data || error.message);
        logger.erorr(`fail create payment: ${error.message}}`);
        throw new AppError(
            `Failed to initiate upload: ${error.message}`,
            error.$metadata?.httpStatusCode || 500
        );
    }
}

module.exports = {
    createInvoice
}